# Generated by Django 4.1.7 on 2023-03-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0003_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='pc_app.comment', verbose_name='Комментарии'),
        ),
    ]
